# public/admin/config.yml
backend:
  name: git-gateway
  branch: main # ou master selon ton repo

media_folder: 'public/uploads'
public_folder: '/uploads'

collections:
  - name: 'articles'
    label: 'Articles'
    folder: 'src/content/articles'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
