# public/admin/config.yml
backend:
  name: git-gateway
  branch: main # ou master selon ton repo

media_folder: 'public/uploads'
public_folder: '/uploads'

collections:
  - name: 'articles'
    label: 'Articles'
    folder: 'src/content/articles'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Image principale', name: 'image', widget: 'image' }
      - {
          label: 'Galerie (optionnel)',
          name: 'gallery',
          widget: 'list',
          field: { label: 'Image', name: 'image', widget: 'image' }
        }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'programme'
    label: 'Programme'
    folder: 'src/content/programme'
    create: true
    slug: '{{slug}}'
    fields:
  - { label: 'Titre (optionnel)', name: 'title', widget: 'string', required: false }
  - { label: 'Date', name: 'date', widget: 'datetime' }
  - { label: 'Contenu (optionnel)', name: 'body', widget: 'markdown', required: false }
  - { label: 'Image (optionnel)', name: 'image', widget: 'image', required: false }
